import { useState } from "react";
import AppContext from "./appContext";
import ResturantContext from "./ResturantContext";
import NightlifeContext from "./nightlifeContext";
const AppState = (props) => {
  const dataInitial = [
    {
      id: 3,
      title: "Mutton Biriyani",
      description: "Delicious and flavorful",
      rating: 4.8,
      discount: 20,
      price: 180,
      time: 25,
      image: "/img1.avif",
      veg: false,
    },
    {
      id: 4,
      title: "KFC",
      description: "KFC Bucket and Biriyani",
      rating: 3.1,
      discount: 15,
      price: 300,
      time: 45,
      image: "/img2.avif",
      veg: false,
    },
    {
      id: 5,
      title: "Pizza",
      description: "Juicy and mouthwatering",
      rating: 4.5,
      discount: 30,
      price: 150,
      time: 30,
      image: "/img3.avif",
      veg: true,
    },
    {
      id: 6,
      title: "Margherita Pizza",
      description: "Fresh and flavorful",
      rating: 3.9,
      discount: 25,
      price: 200,
      time: 35,
      image: "/img4.avif",
      veg: true,
    },
    {
      id: 7,
      title: "All in One",
      description: "Tender and succulent",
      rating: 4.2,
      discount: 10,
      price: 220,
      time: 40,
      image: "/img5.avif",
      veg: false,
    },
    {
      id: 8,
      title: "Non-Veg Thali",
      description: "Fresh and flavorful",
      rating: 3.6,
      discount: 20,
      price: 280,
      time: 50,
      image: "/img6.avif",
      veg: false,
    },
    {
      id: 9,
      title: "Kwality Wall's Frozen Desert",
      description: "Ice Cream, Deserts",
      rating: 3.3,
      discount: 15,
      price: 190,
      time: 30,
      image: "/img7.avif",
      veg: true,
    },
    {
      id: 10,
      title: "Classic Cheeseburger",
      description: "Creamy and indulgent",
      rating: 3.7,
      discount: 25,
      price: 320,
      time: 55,
      image: "/img8.avif",
      veg: false,
    },
    {
      id: 11,
      title: "Noodles with Pizza",
      description: "Zesty and satisfying",
      rating: 3.4,
      discount: 15,
      price: 250,
      time: 40,
      image: "/img9.avif",
      veg: true,
    },
    {
      id: 12,
      title: "HFC Bucket",
      description: "Fresh and flavorful",
      rating: 4.9,
      discount: 20,
      price: 280,
      time: 45,
      image: "/img10.avif",
      veg: false,
    },
    {
      id: 13,
      title: "South Indian Breakfast",
      description: "Sizzling and savory",
      rating: 3.6,
      discount: 10,
      price: 200,
      time: 35,
      image: "/img11.avif",
      veg: true,
    },
    {
      id: 14,
      title: "Garlic Naan",
      description: "Nutritious and refreshing",
      rating: 4.3,
      discount: 30,
      price: 300,
      time: 50,
      image: "/img12.avif",
      veg: false,
    },
    {
      id: 15,
      title: "Puri with Mutton Curry",
      description: "Creamy and comforting",
      rating: 4.8,
      discount: 25,
      price: 270,
      time: 42,
      image: "/img13.avif",
      veg: false,
    },
    {
      id: 16,
      title: "Chicken Sausages",
      description: "Spicy and aromatic",
      rating: 4.5,
      discount: 20,
      price: 260,
      time: 38,
      image: "/img14.avif",
      veg: false,
    },
    {
      id: 17,
      title: "Dish of Hilsha Curry",
      description: "Fresh and satisfying",
      rating: 4.7,
      discount: 15,
      price: 290,
      time: 48,
      image: "/img15.avif",
      veg: false,
    },
  ];

  const resturants = [
    {
      id: 1,
      name: "Pepe Rosa",
      address: "Camac Street",
      situated: "Street Area",
      rating: 4.8,
      price: 1800,
      distance: 25,
      image: "resturant images/img1.avif",
      openNow: true,
      outdoorSeating: false,
    },
    {
      id: 2,
      name: "Sushi Samurai",
      address: "Zen Garden",
      situated: "Cherry Blossom",
      rating: 3.7,
      price: 3000,
      distance: 10,
      image: "resturant images/img2.avif",
      openNow: true,
      outdoorSeating: true,
    },
    {
      id: 3,
      name: "Taco Town",
      address: "Jalapeno Boulevard",
      situated: "Guacamole City",
      rating: 3.2,
      price: 1500,
      distance: 20,
      image: "resturant images/img3.avif",
      openNow: true,
      outdoorSeating: false,
    },
    {
      id: 4,
      name: "Mamma Mia",
      address: "Pasta Avenue",
      situated: "Little Italy",
      rating: 4.5,
      price: 2500,
      distance: 15,
      image: "resturant images/img4.avif",
      openNow: false,
      outdoorSeating: true,
    },
    {
      id: 5,
      name: "Burger Palace",
      address: "Fries Street",
      situated: "Cheese District",
      rating: 3.6,
      price: 1200,
      distance: 18,
      image: "resturant images/img5.avif",
      openNow: true,
      outdoorSeating: true,
    },
    {
      id: 6,
      name: "Pizza Paradise",
      address: "Mozzarella Lane",
      situated: "Pepperoni Plaza",
      rating: 4.9,
      price: 1800,
      distance: 12,
      image: "resturant images/img6.avif",
      openNow: true,
      outdoorSeating: true,
    },
    {
      id: 7,
      name: "Curry Corner",
      address: "Naan Avenue",
      situated: "Spices Street",
      rating: 3.3,
      price: 1000,
      distance: 22,
      image: "resturant images/img7.avif",
      openNow: true,
      outdoorSeating: false,
    },
    {
      id: 8,
      name: "Emily's Kitchen",
      address: "Main Street",
      situated: "Culinary District",
      rating: 4.8,
      price: 2000,
      distance: 8,
      image: "resturant images/img8.avif",
      openNow: false,
      outdoorSeating: true,
    },
    {
      id: 9,
      name: "Taste of Thailand",
      address: "Chili Avenue",
      situated: "Basil Boulevard",
      rating: 4.7,
      price: 2200,
      distance: 14,
      image: "resturant images/img9.avif",
      openNow: true,
      outdoorSeating: false,
    },
    {
      id: 10,
      name: "Steakhouse Supreme",
      address: "Ribeye Road",
      situated: "Sirloin Street",
      rating: 4.4,
      price: 2800,
      distance: 30,
      image: "resturant images/img10.avif",
      openNow: false,
      outdoorSeating: true,
    },
    {
      id: 11,
      name: "Seafood Sensation",
      address: "Lobster Lane",
      situated: "Shrimp Square",
      rating: 3.6,
      price: 1900,
      distance: 25,
      image: "resturant images/img11.avif",
      openNow: true,
      outdoorSeating: false,
    },

    {
      id: 12,
      name: "Veggie Delight",
      address: "Garden Green",
      situated: "Veggie Valley",
      rating: 4.9,
      price: 1500,
      distance: 17,
      image: "resturant images/img12.avif",
      openNow: true,
      outdoorSeating: false,
    },
  ];

  const nightlife = [
    {
      id: 1,
      name: "Pepe Rosa",
      address: "Camac Street",
      situated: "Street Area",
      rating: 3.8,
      price: 1800,
      distance: 25,
      image: "nightlife images/pic2.avif",
      openNow: true,
      outdoorSeating: false,
      gold: true,
    },
    {
      id: 5,
      name: "Sunset Grill",
      address: "789 Beach Boulevard",
      situated: "Seaside",
      rating: 4.7,
      price: 2500,
      distance: 30,
      image: "nightlife images/pic3.avif",
      openNow: true,
      outdoorSeating: true,
      gold: false,
    },
    {
      id: 6,
      name: "Coffee Haven",
      address: "321 Park Avenue",
      situated: "Park District",
      rating: 4.4,
      price: 1200,
      distance: 5,
      image: "nightlife images/pic4.avif",
      openNow: true,
      outdoorSeating: true,
      gold: false,
    },
    {
      id: 7,
      name: "Downtown Diner",
      address: "456 Maple Street",
      situated: "Downtown",
      rating: 3.6,
      price: 1800,
      distance: 10,
      image: "nightlife images/pic5.avif",
      openNow: true,
      outdoorSeating: false,
      gold: true,
    },
    {
      id: 8,
      name: "Ocean's Edge",
      address: "123 Coastline Drive",
      situated: "Oceanfront",
      rating: 4.9,
      price: 2200,
      distance: 15,
      image: "nightlife images/pic6.avif",
      openNow: true,
      outdoorSeating: true,
      gold: false,
    },
    {
      id: 9,
      name: "Moonlight Lounge",
      address: "789 Crescent Avenue",
      situated: "Rooftop",
      rating: 4.5,
      price: 2000,
      distance: 20,
      image: "nightlife images/pic7.avif",
      openNow: true,
      outdoorSeating: false,
      gold: true,
    },
    {
      id: 10,
      name: "Starlight Bistro",
      address: "567 Galaxy Road",
      situated: "Skyline",
      rating: 3.7,
      price: 2400,
      distance: 25,
      image: "nightlife images/pic8.avif",
      openNow: true,
      outdoorSeating: true,
      gold: false,
    },
    {
      id: 11,
      name: "Sunrise Café",
      address: "890 Dawn Drive",
      situated: "Sunrise Point",
      rating: 3.9,
      price: 1900,
      distance: 10,
      image: "nightlife images/pic9.avif",
      openNow: true,
      outdoorSeating: false,
      gold: true,
    },
    {
      id: 12,
      name: "Lakeside Retreat",
      address: "234 Lakeview Terrace",
      situated: "Lakeside",
      rating: 4.8,
      price: 2100,
      distance: 12,
      image: "nightlife images/pic10.avif",
      openNow: true,
      outdoorSeating: true,
      gold: false,
    },
    {
      id: 13,
      name: "Mountain View Grill",
      address: "345 Summit Avenue",
      situated: "Mountaintop",
      rating: 4.6,
      price: 2300,
      distance: 18,
      image: "nightlife images/pic11.avif",
      openNow: true,
      outdoorSeating: true,
      gold: true,
    },
    {
      id: 14,
      name: "Parkside Pub",
      address: "678 Park Street",
      situated: "Parkside",
      rating: 4.4,
      price: 1800,
      distance: 8,
      image: "nightlife images/pic12.avif",
      openNow: true,
      outdoorSeating: false,
      gold: false,
    },
    {
      id: 15,
      name: "Riverfront Café",
      address: "901 River Road",
      situated: "Riverfront",
      rating: 4.7,
      price: 1950,
      distance: 13,
      image: "nightlife images/pic13.avif",
      openNow: true,
      outdoorSeating: true,
      gold: true,
    },
    {
      id: 16,
      name: "Cityscape Lounge",
      address: "123 Metropolitan Avenue",
      situated: "City Center",
      rating: 4.5,
      price: 2050,
      distance: 14,
      image: "nightlife images/pic14.avif",
      openNow: true,
      outdoorSeating: false,
      gold: false,
    },
    {
      id: 17,
      name: "Garden Terrace",
      address: "567 Blossom Boulevard",
      situated: "Garden District",
      rating: 4.8,
      price: 2150,
      distance: 17,
      image: "nightlife images/pic15.avif",
      openNow: true,
      outdoorSeating: true,
      gold: true,
    },
  ];

  const [data, setData] = useState(dataInitial);
  const [resturant, setResturan] = useState(resturants);
  const [nightlifes, setNightlifes] = useState(nightlife);
  return (
    <AppContext.Provider value={{ data, setData }}>
      <ResturantContext.Provider value={{ resturant, setResturan }}>
        <NightlifeContext.Provider value={{ nightlifes, setNightlifes }}>
          {props.children}
        </NightlifeContext.Provider>
      </ResturantContext.Provider>
    </AppContext.Provider>
  );
};

export default AppState;
